config/routes.rb
Juniors::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products
  resources :registrations do
    resources :payments, :only => [:new, :create, :edit, :update] do
      member do
        get 'paypal'
      end
    end
    member do
      post 'confirm'
    end
  end
  
  post 'payments/ipn', :to => 'payments#ipn'

  get 'pages/index'
  get 'pages/about'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/calendar'
  get 'pages/datatable'
  
  root :to => 'pages#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "The person #{@user.email} was removed"
    redirect_to users_path
  end 
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    if @user.save
      flash[:success] = "Changes to person #{@user.email} were saved"
      redirect_to users_path
    else
      render 'edit'
    end
  end 
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Added person #{@user.email} to your account"
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def index
    @users = User.all
    render 'index'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/edit.html.erb
<h1>Change <%= @user.email %></h1>

<%= form_for @user, :url => { :action => :update } do |f| %>
	<%= render 'shared/errors',  :object => @user %>
	<%= render 'fields', :f => f %>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/index.html.erb
<h1>Admin users</h1>
<table>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.email %></td>
				<td><%= user.created_at %></td>
				<td style="width:1%;white-space:nowrap">
					<%= link_to 'Change', edit_user_path(user) %> | 
					<%= link_to 'Remove', user_path(user), :confirm => "Are you sure? #{user.email} will be permanently removed", :method => :delete %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<p><%= link_to 'Add user &raquo;'.html_safe, new_user_path %>

app/views/users/new.html.erb
<h1>Add an administrator</h1>

<%= form_for @user do |f| %>
	<%= render 'shared/errors',  :object => @user %>
	<%= render 'fields', :f => f %>
  <div class="actions"><%= f.submit %></div>
<% end %>