config/routes.rb
Juniors::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products
  resources :registrations do
    resources :payments, :only => [:new, :create, :edit, :update] do
      member do
        get 'paypal'
      end
    end
    member do
      post 'confirm'
    end
  end
  
  post 'payments/ipn', :to => 'payments#ipn'

  get 'pages/index'
  get 'pages/about'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/calendar'
  get 'pages/datatable'
  
  root :to => 'pages#index'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name,
    :presence => true
    
  validates :price, 
    :numericality => true, 
    :presence => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.update_attributes(params[:product])
    if @product.save
      flash[:success] = 'The product was saved'
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(params[:product])
    if @product.save
      flash[:success] = 'The product was saved'
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def index
    @products = Product.find(:all)
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = 'The product was removed'
    redirect_to(products_path)    
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	<%= render 'shared/errors', :object => @product %>
	<fieldset>
		<legend>Product details</legend>
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name, :class => :text %>
		</div>
		<div class="field">
			<%= f.label :description %>
			<%= f.text_area :description, :class => :text %>			
		</div>
		<div class="field">
			<%= f.label :price, 'Price (in dollars)' %>
			<%= f.text_field :price, :class => 'text small' %>
		</div>
		<div class="field">
			<%= f.label :category, 'category' %>
			<%= f.text_field :category, :class => 'text small' %>
		</div>
		<div class="field">
			<%= f.label :session, 'Session' %>
			<%= f.text_field :session, :class => 'text small' %>
		</div>
		<div class="field">
			<div class="checkbox">
				<%= f.check_box :enabled %>
				<%= f.label :enabled, 'Enabled?', :class => :text %>
			</div>
		</div>
		<div class="actions">
			<%= f.submit 'Save' %>
			or <%= link_to 'Cancel', products_path %>
		</div>
	</fieldset>
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>
<p>
	<%= link_to 'New product &raquo;'.html_safe, new_product_path %>
</p>
<% if @products.any? %>
	<table>
		<thead>
			<tr>
				<th>Product</th>
				<th>Description</th>
				<th>Price</th>
				<th>Category</th>
				<th>Enabled?</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |p| %>
				<tr>
					<td><%= link_to p.name, product_path(p) %></td>
					<td><%= p.description %></td>
					<td><%= p.price %></td>
					<td><%= p.category %></td>
					<td><%= p.enabled %></td>
					<td class="actions">
						<%= link_to 'Change', edit_product_path(p) %>
						| <%= link_to 'Remove', product_path(p), :confirm => "This product #{p.name} will be removed. There is no undo. ", :method => :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>No products!</p>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1>Details for <%= @product.name %></h1>

<p>
	<%= link_to 'Back to products', products_path %>
	| <%= link_to 'Change', edit_product_path(@product) %>
	| <%= link_to 'Remove', product_path(@product), :confirm => "This product #{@product.name} will be removed. There is no undo. ", :method => :delete %>
</p>

<table class="first_column_fixed">
	<tbody>
		<tr>
			<td>Product: </td>
			<td><%= @product.name %></td>
		</tr>
		<tr>
			<td>Description: </td>
			<td><%= @product.description %></td>
		</tr>
		<tr>
			<td>Price: </td>
			<td><%= @product.price %></td>
		</tr>
		<tr>
			<td>Session: </td>
			<td><%= @product.session %></td>
		</tr>
		<tr>
			<td>Enabled?: </td>
			<td><%= @product.enabled? %></td>
		</tr>
	</tbody>
</table>