config/routes.rb
Juniors::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products
  resources :registrations do
    resources :payments, :only => [:new, :create, :edit, :update] do
      member do
        get 'paypal'
      end
    end
    member do
      post 'confirm'
    end
  end
  
  post 'payments/ipn', :to => 'payments#ipn'

  get 'pages/index'
  get 'pages/about'
  get 'pages/privacy'
  get 'pages/contact'
  get 'pages/calendar'
  get 'pages/datatable'
  
  root :to => 'pages#index'
  

end

app/views/layouts/_navigation.html.erb
<ul>
  <li><%= link_to "Home", pages_index_path, :class => "index" %></li>
  <li><%= link_to "Register", new_registration_path, :class => "register" %></li>
  <li><%= link_to "Calendar", pages_calendar_path, :class => "calendar" %></li>
  <li><%= link_to "About", pages_about_path, :class => "about" %></li>
  <li><%= link_to "Privacy", pages_privacy_path, :class => "privacy" %></li>
  <li><%= link_to "Contact us", pages_contact_path, :class => "contact" %></li>
  <li>
		<% if current_user %>
			<%= link_to "Sign out", session_path(current_user), :method => :delete, :class => "logout last" %>
		<% else %>
			<%= link_to "Sign in", new_session_path, :class => "login last" %>
		<% end %>
	</li>
</ul>
<%= content_tag(:div, current_user.email, :class => 'identity') if current_user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lakeville junior volleyball</title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'style',  :media => 'screen' %>
  <!--[if IE]><link rel="stylesheet" href="blueprint/ie.css" type="text/css" media="screen, projection" /><![endif]-->  
  <%= javascript_include_tag 'jquery.min', 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= "#{controller.controller_name} #{controller.action_name}" %>">
  <div class="container">
    <div id="header" class="span-24 last">
    	<div class="banner">
        <h1><%= link_to "Lakeville Juniors", pages_index_path, :title => 'home' %></h1>
        <h2><%= link_to "[ youth volleyball club ]", pages_index_path, :title => 'home' %></h2>
      </div>
      
    </div>
    <div id="navigation" class="span-24	last"><%= render :partial => 'layouts/navigation' %></div>
		<div id="wrapper" class="span-24">
			
			<div class="span-17">
				<div id="content">
					<%= render 'shared/show_flash' %>
					<%= yield %>
				</div>
			</div>
			
			<div class="span-7 last">
				<div id="aside">
					<% if current_user %>
					  <h4>Admin</h4>
						<ul>
							<li><%= link_to 'Users', users_path %></li>
							<li><%= link_to 'Products', products_path %></li>
							<li><%= link_to 'Registrations', registrations_path %></li>
							<li><%= link_to 'All info', pages_datatable_path %></li>
						</ul>
					<% end %>
					<h4>Volleyball links</h4>
				  <ul>
				    <li><a href="http://www.lakevillenorthjuniors.com/">Lakeville North Juniors</a></li>
				    <li><a href="http://www.lakevillesouthjuniors.com/">Lakeville South Juniors</a></li>
				    <li><a href="http://www.ncrusav.org/">North Country - USA Volleyball</a></li>
				  </ul>
				</div>
			</div>
		</div>
		<div id="footer" class="span-24 last clear">
			<div>Copyright - <%= Date.today.year.to_s + " " + APP_LONG_NAME %></div>
		</div>
  </div>
  <% if Rails.env.development? %>
		<div class='debug'>
	    <div class="span-24"><%= debug(params) %></div>
	    <div class="span-24"><%= debug(session) %></div>
		</div>
  <% end %>
</body>
</html>

app/views/layouts/application_popout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lakeville junior volleyball</title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'style',  :media => 'screen' %>
  <!--[if IE]><link rel="stylesheet" href="blueprint/ie.css" type="text/css" media="screen, projection" /><![endif]-->  
  <%= javascript_include_tag 'jquery.min', 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= "#{controller.controller_name} #{controller.action_name}" %>" style="background:none;">
  <div>
					<%= yield %>
  </div>
  <% if Rails.env.development? %>
		<div class='debug'>
	    <div class="span-24"><%= debug(params) %></div>
	    <div class="span-24"><%= debug(session) %></div>
		</div>
  <% end %>
</body>
</html>

app/views/layouts/application_wide.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lakeville junior volleyball</title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'style',  :media => 'screen' %>
  <!--[if IE]><link rel="stylesheet" href="blueprint/ie.css" type="text/css" media="screen, projection" /><![endif]-->  
  <%= javascript_include_tag 'jquery.min', 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= "#{controller.controller_name} #{controller.action_name}" %>">
  <div class="container">
    <div id="header" class="span-24 last">
    	<div class="banner">
        <h1><%= link_to "Lakeville Juniors", pages_index_path, :title => 'home' %></h1>
        <h2><%= link_to "[ youth volleyball club ]", pages_index_path, :title => 'home' %></h2>
      </div>
      
    </div>
    <div id="navigation" class="span-24	last"><%= render :partial => 'layouts/navigation' %></div>
		<div id="wrapper" class="aside_not span-24">
			
			<div class="span-17">
				<div id="content">
					<%= render 'shared/show_flash' %>
					<%= yield %>
				</div>
			</div>
			
		</div>
		<div id="footer" class="span-24 last clear">
			<div>Copyright - <%= Date.today.year.to_s + " " + APP_LONG_NAME %></div>
		</div>
  </div>
  <% if Rails.env.development? %>
		<div class='debug'>
	    <div class="span-24"><%= debug(params) %></div>
	    <div class="span-24"><%= debug(session) %></div>
		</div>
  <% end %>
</body>
</html>